# Generated by Django 6.1.1 on 2026-10-01 08:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('base_path', models.CharField(default='/v1', max_length=60)),
                ('is_public', models.BooleanField(default=False)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('tags_text', models.CharField(blank=True, default='', max_length=500)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], default='GET', max_length=7)),
                ('path', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('mock_enabled', models.BooleanField(default=False)),
                ('mock_status', models.PositiveSmallIntegerField(default=200)),
                ('mock_body', models.JSONField(blank=True, default=dict)),
                ('target_url', models.URLField(blank=True, max_length=500)),
                ('request_count', models.BigIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='apis.apiproject')),
            ],
            options={
                'ordering': ('path',),
            },
        ),
        migrations.AddIndex(
            model_name='apiproject',
            index=models.Index(fields=['owner', '-created_at'], name='apis_apipro_owner_i_c66e17_idx'),
        ),
        migrations.AddIndex(
            model_name='apiproject',
            index=models.Index(fields=['slug'], name='apis_apipro_slug_8c2132_idx'),
        ),
        migrations.AddConstraint(
            model_name='apiproject',
            constraint=models.UniqueConstraint(fields=('owner', 'slug'), name='unique_slug_per_owner'),
        ),
        migrations.AddIndex(
            model_name='endpoint',
            index=models.Index(fields=['project', 'method', 'path'], name='apis_endpoi_project_8de43c_idx'),
        ),
        migrations.AddConstraint(
            model_name='endpoint',
            constraint=models.UniqueConstraint(fields=('project', 'method', 'path'), name='unique_method_path_per_project'),
        ),
    ]
